### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/l10n-netherlands#118]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] l10n_nl_bank
- [x] l10n_nl_bsn
- [ ] l10n_nl_cbs_export
- [ ] l10n_nl_intrastat
- [ ] l10n_nl_partner_name
- [ ] l10n_nl_partner_salutation
- [ ] l10n_nl_postcodeapi
- [x] l10n_nl_tax_statement
- [x] l10n_nl_xaf_auditfile_export

**Comment by astirpe** [comment]
l10n_nl_bsn https://github.com/OCA/l10n-netherlands/pull/123

**Comment by astirpe** [comment]
l10n_nl_xaf_auditfile_export https://github.com/OCA/l10n-netherlands/pull/124

**Comment by astirpe** [comment]
l10n_nl_tax_statement https://github.com/OCA/l10n-netherlands/pull/126

**Comment by melroy89** [comment]
l10n_nl_bsn is already merged. Mark as done.

**Comment by melroy89** [comment]
l10n_nl_tax_invoice_basis is missing in the above list, but PR is created #122. AND merged.

**Comment by melroy89** [comment]
#124 and #126 is merged.

**Comment by astirpe** [comment]
l10n_nl_cbs_export #152

**Comment by astirpe** [comment]
- `l10n_nl_bank`: https://github.com/OCA/l10n-netherlands/pull/170
- `l10n_nl_cbs_export`: https://github.com/OCA/l10n-netherlands/pull/152
- `l10n_nl_postcodeapi`: https://github.com/OCA/l10n-netherlands/pull/168
- `l10n_nl_intrastat` proposed to be replaced by `l10n_nl_tax_statement_icp`: #151

**Comment by astirpe** [comment]
This issue can be closed
