### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-netherlands#363]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] l10n_nl_account_tax_unece - By @hbrunn - #417
- [x] l10n_nl_bank - By @astirpe - #386
- [x] l10n_nl_bsn - By @astirpe - #374
- [x] l10n_nl_postcode - By @astirpe - #373
- [x] l10n_nl_tax_statement - By @astirpe - #372
- [x] l10n_nl_xaf_auditfile_export - By @astirpe - #371

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by gjotten** [comment]
- [ ]  l10n_nl_xaf_auditfile_export is otherwise paywalled in Odoo Enterprise, so for non-EE accounting implementations we definitely need that one migrated as well AFAICS?

**Comment by NL66278** [comment]
The auditfile should be first migrated to 15.0 then.

**Comment by ddejong-therp** [comment]
It looks like `l10n_nl_bank` has been migrated already.
